version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    cooldown:
      semver-major-days: 60
      semver-minor-days: 14
      semver-patch-days: 14
    schedule:
      interval: "weekly"
